"""
Django settings for focusgreen project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# ==============================================
# 🌿 Caminhos do projeto
# ==============================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================
# 🌿 Variáveis de ambiente (.env)
# ==============================================

# Carrega as variáveis do arquivo .env na raiz do projeto
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Recupera a chave da API da OpenAI (ou outras futuras)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# (Opcional) Verificação para garantir que a variável foi carregada
if not OPENAI_API_KEY:
    raise ValueError("🚨 ERRO: A variável OPENAI_API_KEY não foi encontrada. Verifique o arquivo .env!")

# ==============================================
# ⚙️ Configurações básicas do Django
# ==============================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ==============================================
# 🧩 Aplicativos instalados
# ==============================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "accounts",
    "tracker",
    "dashboard",
    "assistant",
]

# ==============================================
# ⚙️ Middlewares
# ==============================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "focusgreen.urls"

# ==============================================
# 🧱 Templates
# ==============================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],  # estrutura organizada por app
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "focusgreen.wsgi.application"

# ==============================================
# 🗄️ Banco de dados
# ==============================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ==============================================
# 🔐 Autenticação
# ==============================================

LOGIN_REDIRECT_URL = 'profile'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# ==============================================
# 🔒 Validação de senhas
# ==============================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ==============================================
# 🌎 Localização
# ==============================================

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

# ==============================================
# 🖼️ Arquivos estáticos
# ==============================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# ==============================================
# 🔑 Campo padrão de ID
# ==============================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"