# Generated by Django 5.2.7 on 2025-10-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreenTimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("minutes", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[("PROD", "Produtivo"), ("NAO_PROD", "Não Produtivo")],
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de tempo",
                "verbose_name_plural": "Registros de tempo",
                "ordering": ["-started_at"],
            },
        ),
    ]
